/**
 * 每条 lint 规则的「怎么修」——按规则码索引的兜底修法。
 *
 * 为什么要有它：lint 消息此前只有约六分之一带修法（24/153 个 emit 点），其余只说「什么不对」。
 * 而「怎么修」在全仓的唯一陈述处是 using-ccm 的规则速查表——一份要靠人锁步维护的副本。
 * 把修法放进引擎，让报错自己说清补救动作：接口不会过期，副本会。
 *
 * 怎么用：emit() 在消息本身未含「怎么修」时自动追加本表对应项。因此
 *   - 单点特化的修法：直接写进该处 emit 的消息（本表不覆盖它）；
 *   - 一条规则的通用修法：写在本表，该规则的全部 emit 点自动获得。
 *
 * 硬约束：非 reserved 的规则必须在此有条目、或在它的每个 emit 点自带修法，
 * 由 board-lint-remediation.test.ts 机械把关——新增规则不许再裸奔。
 */
export const RULE_REMEDIATION: Readonly<Record<string, string>> = Object.freeze({
  'BIZ-ACCEPTANCE-REQUIRED': `这些 type 必须带 \`--accept\``,
  'BIZ-AGILE-ACCEPTANCE-MISSING': `给该 member 补一句 DoD 或 criteria；没有验收标准的节点不该作为可 ship 切片收口`,
  'BIZ-AWAITING': `\`task block --on user --decision @file\`，必须带采访包`,
  'BIZ-CADENCE-CRITICAL-PATH-OVER': `重切临界链上的大节点，删假依赖边，或把 scope/timebox 取舍 surface 给用户`,
  'BIZ-CADENCE-MISSING-ESTIMATE': `给 member 补 \`--estimate 3h\` 这类估时，或移出本轮；否则 overbook / critical-path 判断会失明`,
  'BIZ-CADENCE-OVERBOOKED': `拆小、移出非本轮 member、降低 WIP 后重排；不要用 shipped 掩盖超载`,
  'BIZ-CADENCE-SHIPPED': `先把成员推到 done+verified 再 \`ccm cadence ship\`，或移出 members`,
  'BIZ-DEADLINE-OVERDUE': `按 \`kind\` 分档响应，判据一致：**\`soft\`（软目标）超期 → advisory nudge**（提示但不阻断·同步进度/剩余交付物后可继续推进·软目标超期不强制停派）；**\`hard\`（硬承诺）超期 → directive**（须先向用户报告状态/剩余交付物/方案，由用户裁决延期 \`ccm goal deadline amend --user-authorized\` / 缩范围 \`ccm goal amend\` / 分阶段 / 终止）。两档都别静默降验收/伪造完成`,
  'BIZ-DEADLINE-PENDING': `拆 DAG 前先 \`ccm goal deadline set/confirm\`（确认交付截止期）或 \`ccm goal deadline confirm-none\`（确认无 DDL）`,
  'BIZ-DECISION-PACKAGE': `备齐采访包字段；decision 型必须有非空 options`,
  'BIZ-DELIVERY-CANDIDATE-BINDING': `\`done→stale\` 可留证据审计但不会 qualify；\`retry\` 会原子归档并清空，开新 attempt 后重新 attest；不得伪造 fingerprint 或复用旧 candidate`,
  'BIZ-DELIVERY-IMPACT': `跑任意 ccm 写命令触发 reconcile，使状态回到 declared truth 后补 proof`,
  'BIZ-DELIVERY-PROOF': `跑 \`dependency explain\` 看 containment、drift、missing-object、review 或 waiver diagnostic`,
  'BIZ-DEPENDENCY-REQUIREMENT': `删除/改正陈旧 requirement；metadata 不会创建隐藏 DAG edge`,
  'BIZ-DEV-REFS': `development task 加 \`--ref spec:/abs/spec.md --ref plan:/abs/plan.md\`（\`task add\`）或 \`--add-ref\`（\`task update\`）；\`--force\` 可越`,
  'BIZ-DONE-VERIFIED': `\`task done --verified --artifact /abs/...\`;若尚未端点验收或没有产物,不要标 \`done\``,
  'BIZ-ESTIMATE-STALE': `用新的实测反馈重估未开始下游，必要时重开 baseline / replan`,
  'BIZ-EXECUTOR-HANDLE': `legacy 派发工具返回句柄后 \`task update --handle <后台句柄>\`，再转 \`in_flight\`；\`ready\` / \`blocked\` future task 不预填；native attempt 只走 dedicated writer，由 hard rule 接管`,
  'BIZ-EXTERNAL-ARTIFACT': `把 artifact 改成外部实际产出（PR / commit / release / report / CI run）；若 issue closed 但尚未验收，别标 done，先用 \`uncertain\` / \`in_flight\` / \`stale\``,
  'BIZ-EXTERNAL-ISSUE': `external task 加 \`--ref issue:https://github.com/o/r/issues/N\` 做外部追踪锚点`,
  'BIZ-GOAL-PENDING': `先澄清并用 \`ccm goal set\` / \`goal amend\` settle，再切 DAG / 派发；等待用户时只保留完整 \`blocked_on:user\` \`decision_package\``,
  'BIZ-INFLIGHT-AGENT': `凡派发皆登记：\`ccm agent create\` + \`ccm agent link <agent-id> --task <task-id>\` 补登记，让花名册 / viewer 能观测这次派发`,
  'BIZ-NATIVE-ATTEMPT-PROJECTION': `不手改、不用 generic verb 或 \`--force\` 修；只走 \`native-attempt-create/bind/cancel/terminal/reconcile\`，让认证 evidence 驱动 projection`,
  'BIZ-REVIEW-VERDICT-GATE': `update --review-gate APPROVE\` 声明下游门控语义，再记录 verdict`,
  'BIZ-ROUTE-ATTEMPT-REQUIRED': `selection + running attempt 只经 \`route-bind\` 原子写；attempts append-only，不手改`,
  'BIZ-ROUTE-POLICY-REQUIRED': `用 \`task set-routing\`；candidate 必须满足 planning capability/effect/permission 交叉约束`,
  'BIZ-ROUTE-SELECTION-REQUIRED': `不用 generic start/force；取得 fresh qualification evidence与真实 handle 后走 \`route-bind\``,
  'BIZ-ROUTED-PLANNING-REQUIRED': `先补 estimate，再用 \`task set-planning\` 写完整画像；enabled 新 task 最后才把 executor 定成 subagent`,
  'BIZ-STATUS-DEPS': `**CLI 写路径经 \`reconcileGating\` 永不产生此态**——看到它多半是手改 board；跑任意 ccm 写命令触发归一，或 \`task unblock\`/\`set-status\` 手动对齐`,
  'BIZ-TASK-OVERSIZED-FOR-CADENCE': `默认再切成能在一个 cadence 目标内验收的薄片；若不能切，写清理由并接受 warn`,
  'BIZ-TIME-ORDER': `用 ccm verb（\`start\`/\`done\`）按序盖戳，别手填出乱序时间`,
  DELIVERY_SIZE_CAP: `拆 board / 归档旧 attempt；不要用超大 metadata 把 board 变成 evidence store`,
  'FMT-ACCEPTANCE': `\`--accept "一句话"\` 或 \`--set-json acceptance={criteria:[...]}\``,
  'FMT-AGENTS': `手工登记只用 \`ccm agent create/bind/link/terminal/probe\`，tracked worker 用 \`ccm worker dispatch\` 专用 writer；别 \`--set-json\` 手拼。graceful：坏形状不拦普通 lint 写盘，但 tracked aggregate rehydrate 会额外拒绝伪造 running、缺 PID evidence 或跨 task link`,
  'FMT-BASELINE': `用 \`ccm baseline snapshot/reset\` 维护、别手拼；时间严格 UTC（estimate evm 读它，格式不对则 EVM 时间轴错位）`,
  'FMT-BLOCKED-ON': `\`task block --on user\` 或 \`--on <存在的 taskid>\``,
  'FMT-CADENCE': `用 \`ccm cadence update/open/ship\`；deadline 严格 UTC`,
  'FMT-CONTRACTS': `只用 \`ccm board enable-contract\` 成对启用；两者都缺就是合法 legacy；不要手写 \`meta.contracts\``,
  'FMT-COORD': `全 optional·缺即降级（\`ccm peers\` 把该维度退 null）；priority 仅五挡——非法值退化为 normal。永不 hard（advisory ✎·fail-safe）`,
  'FMT-DEADLINE': `只用 \`ccm goal deadline set/confirm/confirm-none/amend\` 写（`,
  'FMT-DELIVERY-CONTRACT': `用 \`target set/refresh\`；只持久化 \`mode:declared\`，strict 仅 dry-run preview`,
  'FMT-DEPENDENCY-GATE': `update --review-gate APPROVE\` 声明；非法 gate fail closed`,
  'FMT-DEPENDENCY-REQUIREMENTS': `用 \`dependency require/default/waive\`；qualification 永远读取时派生`,
  'FMT-DEPS': `deps 是钉死窄腰字段，必填；无上游写 \`--deps\`（空数组），有上游 \`--deps T1,T2\``,
  'FMT-ESTIMATE': `\`--estimate 3h\`（ccm 自动解析成对象），别手拼`,
  'FMT-EXECUTOR': `\`--executor\` ∈ {user, master-orchestrator, subagent, workflow, external}`,
  'FMT-GIT': `\`ccm board update --branch / --worktree\`，值都是字符串`,
  'FMT-GOAL': `\`ccm board init --goal "..."\` / \`ccm board update --goal "..."\`，goal 永远是字符串（空串也合法）`,
  'FMT-GOAL-CONTRACT': `只用 \`ccm goal set / confirm / amend\` 写；Brief 路径与 hash 另由 \`ccm goal check\` 校验`,
  'FMT-HARNESS': `不手填；ARM 时由 \`ccm board stamp-harness\` 从可信 harness env 写入。缺失向后兼容为 \`unknown\`；坏值只 warn，\`ccm peers\` 按 unknown 单例池降级`,
  'FMT-ID': `\`ccm task add <id>\` 的 id 必填非空`,
  'FMT-ID-UNIQUE': `id 全局唯一；不要复制粘贴 task 忘改 id`,
  'FMT-INBOX': `缺失 = 空 inbox；append 用 \`ccm coordination notify\`，消费用 \`ccm coordination inbox ack <id...>\`，不要手拼。\`kind\` 闭集、\`status\` 单调；坏形态只 warn，读取侧跳过坏条目`,
  'FMT-JSON': `用 ccm 写盘（写入校验挡大多数手写坏 JSON）；手改时检查逗号/括号配对`,
  'FMT-JUDGMENT-CALLS': `用 \`ccm jc add/resolve\` 而非手拼`,
  'FMT-LOG': `\`ccm log add "<summary>" --kind <enum>\`；ts 自动盖严格 UTC，summary 非空`,
  'FMT-META': `meta 由 bootstrap 写，别手改；template_version 是整数`,
  'FMT-MODEL': `从 fresh \`ccm provider facts\` 与 live admission 取得实际 selector 后，\`ccm task update <id> --set model=<admitted-provider-model-id>\`（裸 path 即本 task）；非 string → estimate 层 tier 分层校准降级忽略`,
  'FMT-OWNER': `别手改 owner——它是武装闸读的；session_id 空串 \`""\` 合法（待显式 re-arm 认领）`,
  'FMT-PARENT': `\`--parent <ownerId>\`（单个存在的 owner id 字符串），或不写 parent 让它成顶层`,
  'FMT-POLICY': `\`ccm policy set autonomous_account_switch allow|deny\`（写命令视权限为用户所有，非 TTY 须 \`--user-authorized\`）；缺 → 解析为 allow（向后兼容），形状坏 → warn 且仍按 allow 走`,
  'FMT-REF': `\`--ref kind:/abs/path\` 或 \`--ref kind:https://...\`，**禁相对路径**`,
  'FMT-REF-KIND': `kind ∈ {spec, plan, doc, web, code, issue, other}，未知值不致命`,
  'FMT-REVIEW-VERDICT': `REQUEST-CHANGES\`；缺失/null 表示尚无结论`,
  'FMT-ROLE': `\`--role normal\`（默认）或 \`--role fill-work\``,
  'FMT-RUNTIME': `hook-owned ✎ 参数区：用 \`ccm board set-param <白名单 key> <value>\` 写（白名单 + 按 key 声明类型校验在 verb 层·时间锚要 ISO / 指纹要非空字符串）；缺/坏一律 graceful-degrade（周期 hook 退化为「从未提示」·首次必提示；Stop 释放闸退化为继续阻止停止）。未知键 silent-on-unknown。永不 hard`,
  'FMT-SCHEDULING': `\`ccm board update --wip-limit N --owner-wip N\`（整数）；非数字 → WIP 软警告静默关闭`,
  'FMT-SCHEMA': `永远让 bootstrap / ccm 建板，别手写 schema；当前期望值 \`cc-master/v2\``,
  'FMT-STATUS': `status 走 verb（\`task start/done/block/set-status\`），不手写`,
  'FMT-TASK-DELIVERY': `只用 \`task attest-delivery\`；proof 必须精确绑定当前 candidate 与冻结 target snapshot`,
  'FMT-TASK-PLANNING': `用 \`task set-planning --profile\` whole-object writer；enabled subagent 的缺/坏还会升级命中 \`BIZ-ROUTED-PLANNING-REQUIRED\` hard`,
  'FMT-TASK-ROUTING': `用 \`task set-routing --policy\` 建 envelope、\`route-bind\` 写 selection/attempt；enabled subagent 的缺/坏还会命中 route BIZ hard gate`,
  'FMT-TASKS': `tasks 永远是数组（\`[]\` 合法）；用 \`task add\` 而非手拼`,
  'FMT-TIME': `用 ccm verb 自动盖戳（盖标准格式）；手填时严格 UTC 定宽、无时区偏移、无毫秒`,
  'FMT-TYPE': `用已知 type；未知值不致命但可能是 typo，会让基于 type 的 BIZ 规则漏触发`,
  'FMT-WATCHDOG': `先创建真实机制拿 handle，再 \`ccm watchdog arm --mechanism <cron/loop/monitor/shell> --fire-at YYYY-MM-DDTHH:MM:SSZ --job-id <handle>\`；存量缺 handle 先 \`status\` 诊断、\`disarm\` 后重建`,
  'FMT-WIP': `\`--wip-limit N\`（整数）；非数字会让 per-owner WIP 覆写静默失效`,
  'GRAPH-CONNECTED': `为目标聚焦希望图全通（但不强求·warn 非 hard）；给孤岛节点补上指向主图的 deps（它依赖谁 / 谁依赖它），或确认它确实独立后忽略本 warning。消息会列出各分量的 task-id（主图 = 最大分量、其余 = 孤岛）。**连通性 = deps ∪ parent 容器边**（嵌套子任务 \`deps:[]\` 经 owner 连进主图·不误判孤岛）。**\`role:fill-work\` 豁免**（故意独立·从节点集剔除·不 cry-wolf）；**\`awaiting-user\`/决策门不豁免**（本应 gate 某主图工作节点·孤立即真遗漏·用户拍板）`,
  'GRAPH-CYCLE': `打破环——删环上某条 deps 边，让依赖回到无环 DAG`,
  'GRAPH-DANGLING': `dep 必须指向真实存在的上游 id；\`ccm next\` / \`ccm task list\` 先确认 id`,
  'GRAPH-PARENT-CYCLE': `parent 链回到「子单跳指向无 parent 的顶层 owner」`,
  'GRAPH-PARENT-DEPTH': `owner 只能含 leaf 子；孙节点改挂顶层 owner，或把中间节点升为顶层`,
  'GRAPH-PARENT-EXISTS': `parent 指向真实存在的 owner；现有 id 用 \`ccm task list\` 查`,
  'GRAPH-ROLLUP': `确认子全 done + 父端点验收过再标父 done；容许「父整合中、子刚标完」的瞬态`,
  'GRAPH-SELFLOOP': `删掉指向自己的 dep（自环 = 永远 blocked）`,
});
