import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const fixturesRoot = path.join(
  repoRoot,
  'design_docs',
  'skill-knowledge-graph',
  'fixtures',
  'host-portability',
);
const cliPath = path.join(repoRoot, 'scripts', 'skill-knowledge.mjs');

const PRODUCT_HOSTS = Object.freeze(['claude-code', 'codex', 'cursor', 'kimi-code']);
const WORKER_ALLOWLIST = Object.freeze(['codex', 'cursor']);
const PAYLOAD_MODES = Object.freeze(['canonical', 'partial', 'stub']);

function runCli(args) {
  return spawnSync(process.execPath, [cliPath, ...args], {
    cwd: repoRoot,
    encoding: 'utf8',
  });
}

function withTempDir(run) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ccm-skg-host-probe-'));
  try {
    return run(root);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

test('SKG-HOST-01: frozen adapter contract keeps product hosts and worker allowlist distinct', async () => {
  const {
    HOST_ADAPTER_CONTRACT,
    assertHostAdapterContract,
  } = await import('../../scripts/skill-knowledge/host-portability/adapter-contract.mjs');

  assertHostAdapterContract(HOST_ADAPTER_CONTRACT);
  const golden = JSON.parse(
    fs.readFileSync(path.join(fixturesRoot, 'adapter-contract.json'), 'utf8'),
  );
  assert.deepEqual(golden, JSON.parse(JSON.stringify(HOST_ADAPTER_CONTRACT)));
  assert.deepEqual(HOST_ADAPTER_CONTRACT.product_hosts, [...PRODUCT_HOSTS]);
  assert.deepEqual(HOST_ADAPTER_CONTRACT.worker_allowlist, [...WORKER_ALLOWLIST]);
  assert.deepEqual(HOST_ADAPTER_CONTRACT.payload_modes, [...PAYLOAD_MODES]);
  assert.equal(HOST_ADAPTER_CONTRACT.anchor_form, 'explicit-html-id');
  assert.equal(HOST_ADAPTER_CONTRACT.path_policy, 'relative-final-host-path');
  assert.equal(
    HOST_ADAPTER_CONTRACT.claims.heading_autogenerated_slugs,
    'unverifiable',
  );
  assert.equal(HOST_ADAPTER_CONTRACT.claims.live_host_click_through, 'unverifiable');

  for (const host of PRODUCT_HOSTS) {
    const profile = HOST_ADAPTER_CONTRACT.hosts[host];
    assert.equal(profile.role, 'product-host');
    assert.equal(profile.worker_eligible, WORKER_ALLOWLIST.includes(host));
    assert.equal(typeof profile.path_tokens.skill_dir, 'string');
    assert.equal(typeof profile.path_tokens.plugin_root, 'string');
    assert.equal(typeof profile.path_tokens.skill_dir_expands, 'boolean');
    assert.equal(typeof profile.path_tokens.plugin_root_expands, 'boolean');
    assert.ok(Array.isArray(profile.evidence));
    assert.ok(profile.evidence.length > 0);
  }

  assert.throws(
    () => assertHostAdapterContract({
      ...HOST_ADAPTER_CONTRACT,
      worker_allowlist: ['claude-code', 'codex', 'cursor', 'kimi-code'],
    }),
    /worker allowlist|bounded context/i,
  );
});

test('SKG-HOST-02: anchor normalization is deterministic and rejects unsafe ids', async () => {
  const {
    normalizePointAnchor,
    isPortableAnchorId,
  } = await import('../../scripts/skill-knowledge/host-portability/anchors.mjs');

  assert.deepEqual(normalizePointAnchor('point:verification.endpoint-principle'), {
    source_id: 'point:verification.endpoint-principle',
    html_id: 'ccm-k-point-verification-endpoint-principle',
    fragment: '#ccm-k-point-verification-endpoint-principle',
    html: '<a id="ccm-k-point-verification-endpoint-principle"></a>',
  });
  assert.equal(
    isPortableAnchorId('ccm-k-point-verification-endpoint-principle'),
    true,
  );
  assert.equal(isPortableAnchorId('Point:Verification'), false);
  assert.equal(isPortableAnchorId('heading-only-slug'), false);
  assert.throws(() => normalizePointAnchor('POINT:Bad'), /fail closed|invalid/i);
  assert.throws(() => normalizePointAnchor('related_to'), /fail closed|invalid/i);
});

test('SKG-HOST-03: checked-in fixtures prove link/anchor/path behavior per host and payload', async () => {
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  for (const host of PRODUCT_HOSTS) {
    for (const mode of PAYLOAD_MODES) {
      const payloadRoot = path.join(fixturesRoot, 'payloads', mode);
      const result = probeHostPayload({
        host,
        mode,
        payloadRoot,
        repoRoot,
      });
      assert.equal(result.ok, true, `${host}/${mode}: ${JSON.stringify(result.diagnostics)}`);
      assert.equal(result.host, host);
      assert.equal(result.mode, mode);
      assert.equal(result.summary.errors, 0);
      if (mode === 'stub') {
        assert.equal(result.summary.point_anchors, 0);
        assert.equal(result.claims_point_coverage, false);
      } else {
        assert.ok(result.summary.point_anchors >= 1, `${host}/${mode} needs point anchors`);
        assert.ok(result.summary.resolved_links >= 1, `${host}/${mode} needs resolved links`);
      }
    }
  }
});

test('SKG-HOST-04: probe fails closed on broken links, heading-only targets, and host tokens', async () => {
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  withTempDir((root) => {
    const broken = path.join(root, 'broken');
    fs.mkdirSync(path.join(broken, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      path.join(broken, 'skills', 'demo', 'SKILL.md'),
      [
        '# Broken',
        '',
        '[missing](./missing.md#ccm-k-point-verification-endpoint-principle)',
        '[heading only](#Endpoint-principle)',
        'See `${CLAUDE_PLUGIN_ROOT}/skills/demo/SKILL.md`',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'codex',
      mode: 'canonical',
      payloadRoot: broken,
      repoRoot,
    });
    assert.equal(result.ok, false);
    const codes = result.diagnostics.map((item) => item.code).sort();
    assert.ok(codes.includes('SKG-HOST-LINK-TARGET-MISSING'));
    assert.ok(codes.includes('SKG-HOST-ANCHOR-UNVERIFIABLE'));
    assert.ok(codes.includes('SKG-HOST-PATH-TOKEN-FORBIDDEN'));
  });
});

test('SKG-HOST-05: stub payloads may not claim point coverage via portable anchors', async () => {
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  withTempDir((root) => {
    const stub = path.join(root, 'stub');
    fs.mkdirSync(path.join(stub, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      path.join(stub, 'skills', 'demo', 'SKILL.md'),
      [
        '# Fake stub coverage',
        '',
        '<a id="ccm-k-point-verification-endpoint-principle"></a>',
        '',
        'Pretends the point exists on an unsupported host.',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'cursor',
      mode: 'stub',
      payloadRoot: stub,
      repoRoot,
    });
    assert.equal(result.ok, false);
    assert.equal(
      result.diagnostics.some((item) => item.code === 'SKG-HOST-STUB-FALSE-COVERAGE'),
      true,
    );
  });
});

test('SKG-HOST-06: unknown host and unknown payload mode fail closed', async () => {
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  const unknownHost = probeHostPayload({
    host: 'windsurf',
    mode: 'canonical',
    payloadRoot: path.join(fixturesRoot, 'payloads', 'canonical'),
    repoRoot,
  });
  assert.equal(unknownHost.ok, false);
  assert.equal(unknownHost.diagnostics[0].code, 'SKG-HOST-UNKNOWN');

  const unknownMode = probeHostPayload({
    host: 'claude-code',
    mode: 'overlay',
    payloadRoot: path.join(fixturesRoot, 'payloads', 'canonical'),
    repoRoot,
  });
  assert.equal(unknownMode.ok, false);
  assert.equal(unknownMode.diagnostics[0].code, 'SKG-HOST-PAYLOAD-MODE-UNKNOWN');
});

test('SKG-HOST-07: contract capability flips host_portability_probe on and freezes C9 fields', () => {
  const result = runCli(['contract', '--json']);
  assert.equal(result.status, 0, result.stderr);
  const body = JSON.parse(result.stdout);
  assert.equal(body.capabilities.host_portability_probe, true);
  assert.deepEqual(body.hardening_contract.C9.hosts, [...PRODUCT_HOSTS]);
  assert.deepEqual(body.hardening_contract.C9.worker_allowlist, [...WORKER_ALLOWLIST]);
  assert.deepEqual(body.hardening_contract.C9.payload_modes, [...PAYLOAD_MODES]);
  assert.equal(body.hardening_contract.C9.anchor_form, 'explicit-html-id');
  assert.equal(body.hardening_contract.C9.path_policy, 'relative-final-host-path');
});

test('SKG-HOST-08: partial payload fails when it links outside the projected subset', async () => {
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  withTempDir((root) => {
    const partial = path.join(root, 'partial');
    fs.mkdirSync(path.join(partial, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      path.join(partial, 'skills', 'demo', 'SKILL.md'),
      [
        '# Partial with leak',
        '',
        '[unprojected module](../../modules/verification.md#ccm-k-module-verification-endpoint)',
        '',
        '<a id="ccm-k-skill-demo-entry"></a>',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'kimi-code',
      mode: 'partial',
      payloadRoot: partial,
      repoRoot,
    });
    assert.equal(result.ok, false);
    assert.equal(
      result.diagnostics.some((item) => item.code === 'SKG-HOST-LINK-TARGET-MISSING'),
      true,
    );
  });
});

test('SKG-HOST-09: each product host executes a distinct path-token contract, not a relabel', async () => {
  const {
    HOST_ADAPTER_CONTRACT,
    executeHostTokenContract,
  } = await import('../../scripts/skill-knowledge/host-portability/adapter-contract.mjs');
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  const fingerprints = new Map();
  for (const host of PRODUCT_HOSTS) {
    const executed = executeHostTokenContract(host);
    assert.equal(executed.ok, true, `${host}: ${JSON.stringify(executed.diagnostics)}`);
    assert.equal(executed.host, host);
    assert.ok(Array.isArray(executed.executed_checks));
    assert.ok(
      executed.executed_checks.includes(`token-contract:${host}`),
      `${host} must execute its own token-contract check`,
    );
    assert.ok(
      executed.evidence.every((item) => item.kind === 'document' || item.kind === 'fixture'),
      `${host} evidence must be document|fixture, never live click-through`,
    );
    assert.equal(
      executed.evidence.some((item) => item.kind === 'live-click-through'),
      false,
    );

    const profile = HOST_ADAPTER_CONTRACT.hosts[host];
    const fingerprint = JSON.stringify({
      host,
      path_tokens: profile.path_tokens,
      executed_checks: executed.executed_checks,
      mechanism: profile.path_tokens.plugin_root_mechanism,
    });
    assert.equal(fingerprints.has(fingerprint), false, 'host profiles must not collapse');
    fingerprints.set(fingerprint, host);

    const payloadRoot = path.join(fixturesRoot, 'payloads', 'canonical');
    const probed = probeHostPayload({ host, mode: 'canonical', payloadRoot, repoRoot });
    assert.equal(probed.ok, true, `${host}/canonical: ${JSON.stringify(probed.diagnostics)}`);
    assert.ok(
      probed.executed_checks.includes(`token-contract:${host}`),
      `${host} probe must run host-specific token contract, not only relabel host=`,
    );
    assert.equal(probed.host_profile.path_tokens.plugin_root_mechanism, profile.path_tokens.plugin_root_mechanism);
  }

  assert.equal(fingerprints.size, PRODUCT_HOSTS.length);

  // Grounding against harness facts (executable, not prose-only).
  const claude = executeHostTokenContract('claude-code');
  assert.equal(claude.path_tokens.plugin_root, '${CLAUDE_PLUGIN_ROOT}');
  assert.equal(claude.path_tokens.skill_dir, '${CLAUDE_SKILL_DIR}');
  assert.equal(claude.path_tokens.plugin_root_expands, true);
  assert.equal(claude.path_tokens.skill_dir_expands, true);

  const codex = executeHostTokenContract('codex');
  assert.equal(codex.path_tokens.plugin_root, '${PLUGIN_ROOT}');
  assert.equal(codex.path_tokens.plugin_root_mechanism, 'hook-command-string-token');
  assert.equal(codex.path_tokens.runtime_env_plugin_root, false);
  assert.ok(codex.path_tokens.rejected_fiction_tokens.includes('${CODEX_PLUGIN_ROOT}'));

  const cursor = executeHostTokenContract('cursor');
  assert.equal(cursor.path_tokens.plugin_root_mechanism, 'launcher-plugin-cwd');
  assert.equal(cursor.path_tokens.plugin_root_expands, false);
  assert.equal(cursor.path_tokens.skill_dir_expands, false);
  assert.ok(cursor.path_tokens.rejected_fiction_tokens.includes('${CURSOR_PLUGIN_ROOT}'));
  assert.ok(cursor.path_tokens.rejected_fiction_tokens.includes('${CURSOR_SKILL_DIR}'));

  const kimi = executeHostTokenContract('kimi-code');
  assert.equal(kimi.path_tokens.skill_dir, '${KIMI_SKILL_DIR}');
  assert.equal(kimi.path_tokens.skill_dir_expands, true);
  assert.equal(kimi.path_tokens.plugin_root_mechanism, 'hook-subprocess-env');
  assert.equal(kimi.path_tokens.plugin_root_expands, false);
});

test('SKG-HOST-10: arbitrary ccm-k fragments, a-name anchors, and duplicate ids fail closed', async () => {
  const {
    extractHtmlAnchorIds,
    findDuplicateHtmlAnchorIds,
    isPortableAnchorId,
    normalizePointAnchor,
  } = await import('../../scripts/skill-knowledge/host-portability/anchors.mjs');
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  assert.equal(isPortableAnchorId('ccm-k-garbage'), false);
  assert.equal(isPortableAnchorId('ccm-k-point-verification-endpoint-principle'), true);
  assert.deepEqual(extractHtmlAnchorIds('<a name="ccm-k-point-verification-endpoint-principle"></a>'), []);
  // Only an independent HTML id attribute counts — not *-id lookalikes.
  assert.deepEqual(extractHtmlAnchorIds('<a data-id="ccm-k-skill-demo-entry"></a>'), []);
  assert.deepEqual(extractHtmlAnchorIds('<a aria-id="ccm-k-skill-demo-entry"></a>'), []);
  assert.deepEqual(extractHtmlAnchorIds('<a xml:id="ccm-k-skill-demo-entry"></a>'), []);
  assert.deepEqual(extractHtmlAnchorIds('<a foo-id="ccm-k-skill-demo-entry"></a>'), []);
  assert.deepEqual(
    extractHtmlAnchorIds('<a id="ccm-k-skill-demo-entry"></a>'),
    ['ccm-k-skill-demo-entry'],
  );
  assert.deepEqual(
    findDuplicateHtmlAnchorIds(
      [
        '<a data-id="ccm-k-skill-demo-entry"></a>',
        '<a id="ccm-k-skill-demo-entry"></a>',
      ].join('\n'),
    ),
    [],
  );
  assert.throws(
    () => normalizePointAnchor('point:Verification'),
    /fail closed|invalid/i,
  );

  withTempDir((root) => {
    const payload = path.join(root, 'anchors');
    fs.mkdirSync(path.join(payload, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      path.join(payload, 'skills', 'demo', 'SKILL.md'),
      [
        '# Anchor adversarial',
        '',
        '<a name="ccm-k-point-verification-endpoint-principle"></a>',
        '<a data-id="ccm-k-point-verification-endpoint-principle"></a>',
        '<a aria-id="ccm-k-skill-demo-entry"></a>',
        '<a xml:id="ccm-k-skill-demo-entry"></a>',
        '<a id="ccm-k-skill-demo-entry"></a>',
        '<a id="ccm-k-skill-demo-entry"></a>',
        '',
        '[arbitrary](#ccm-k-garbage)',
        '[name alias target](#ccm-k-point-verification-endpoint-principle)',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'claude-code',
      mode: 'canonical',
      payloadRoot: payload,
      repoRoot,
    });
    assert.equal(result.ok, false);
    const codes = result.diagnostics.map((item) => item.code).sort();
    assert.ok(codes.includes('SKG-HOST-ANCHOR-NAME-ALIAS'));
    assert.ok(codes.includes('SKG-HOST-ANCHOR-DUPLICATE'));
    assert.ok(codes.includes('SKG-HOST-ANCHOR-UNVERIFIABLE'));
    // data-id / aria-id / xml:id must not satisfy the fragment target.
    assert.equal(
      result.diagnostics.some(
        (item) =>
          item.code === 'SKG-HOST-ANCHOR-UNVERIFIABLE' &&
          /ccm-k-point-verification-endpoint-principle/.test(item.message),
      ),
      true,
    );
  });
});

test('SKG-HOST-14: id-like text inside other attribute values is not an HTML id', async () => {
  const { extractHtmlAnchorIds, findDuplicateHtmlAnchorIds } = await import(
    '../../scripts/skill-knowledge/host-portability/anchors.mjs'
  );
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  // Quoted attribute values that merely contain the text `id=…` must not count.
  assert.deepEqual(
    extractHtmlAnchorIds('<a title="not an attribute: id=ccm-k-point-smuggled"></a>'),
    [],
  );
  assert.deepEqual(
    extractHtmlAnchorIds("<a title='not an attribute: id=ccm-k-point-smuggled'></a>"),
    [],
  );
  // Nested opposite-quote smuggling (both quote styles).
  assert.deepEqual(
    extractHtmlAnchorIds(
      `<a title="not an attribute: id='ccm-k-point-smuggled'"></a>`,
    ),
    [],
  );
  assert.deepEqual(
    extractHtmlAnchorIds(
      `<a title='not an attribute: id="ccm-k-point-smuggled"'></a>`,
    ),
    [],
  );
  // Unquoted attribute value containing id=-like text.
  assert.deepEqual(
    extractHtmlAnchorIds('<a title=not:id=ccm-k-point-smuggled></a>'),
    [],
  );
  assert.deepEqual(
    extractHtmlAnchorIds('<a class=id=ccm-k-point-smuggled></a>'),
    [],
  );
  // Greater-than inside a quoted value must not truncate the start tag;
  // genuine independent id still counts, smuggled text still does not.
  assert.deepEqual(
    extractHtmlAnchorIds(
      '<a title="x > y" id="ccm-k-skill-demo-entry"></a>',
    ),
    ['ccm-k-skill-demo-entry'],
  );
  assert.deepEqual(
    extractHtmlAnchorIds(
      `<a title="x > y id='ccm-k-point-smuggled'"></a>`,
    ),
    [],
  );
  // Malformed quoting fail closed — do not salvage a later lookalike.
  assert.deepEqual(
    extractHtmlAnchorIds('<a title="unterminated id="ccm-k-skill-demo-entry"></a>'),
    [],
  );
  // Genuine independent id (and prior exact ccm-k / duplicate grammar) preserved.
  assert.deepEqual(
    extractHtmlAnchorIds('<a id="ccm-k-skill-demo-entry"></a>'),
    ['ccm-k-skill-demo-entry'],
  );
  assert.deepEqual(
    extractHtmlAnchorIds("<a id='ccm-k-skill-demo-entry'></a>"),
    ['ccm-k-skill-demo-entry'],
  );
  assert.deepEqual(
    findDuplicateHtmlAnchorIds(
      [
        '<a title="id=ccm-k-skill-demo-entry"></a>',
        '<a id="ccm-k-skill-demo-entry"></a>',
        '<a id="ccm-k-skill-demo-entry"></a>',
      ].join('\n'),
    ),
    [{ id: 'ccm-k-skill-demo-entry', count: 2 }],
  );

  withTempDir((root) => {
    const payload = path.join(root, 'smuggle');
    fs.mkdirSync(path.join(payload, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      path.join(payload, 'skills', 'demo', 'SKILL.md'),
      [
        '# Smuggled id adversarial',
        '',
        '<a title="not an attribute: id=ccm-k-point-smuggled"></a>',
        `<a title="not an attribute: id='ccm-k-point-smuggled'"></a>`,
        `<a title='not an attribute: id="ccm-k-point-smuggled"'></a>`,
        '<a title=not:id=ccm-k-point-smuggled></a>',
        '',
        '[smuggled](#ccm-k-point-smuggled)',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'claude-code',
      mode: 'canonical',
      payloadRoot: payload,
      repoRoot,
    });
    assert.equal(result.ok, false);
    assert.equal(
      result.diagnostics.some(
        (item) =>
          item.code === 'SKG-HOST-ANCHOR-UNVERIFIABLE' &&
          /ccm-k-point-smuggled/.test(item.message),
      ),
      true,
    );
    assert.equal(
      result.diagnostics.some((item) => item.code === 'SKG-HOST-ANCHOR-DUPLICATE'),
      false,
    );
  });
});

test('SKG-HOST-15: unclosed quoted a-tag must not salvage nested a id or silently recover', async () => {
  const {
    extractHtmlAnchorIds,
    inspectHtmlAnchorIds,
  } = await import('../../scripts/skill-knowledge/host-portability/anchors.mjs');
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  const doubleQuoteSmuggle =
    '<a title="unterminated title <a id="ccm-k-point-smuggled"></a>';
  const singleQuoteSmuggle =
    "<a title='unterminated title <a id='ccm-k-point-smuggled'></a>";

  assert.deepEqual(extractHtmlAnchorIds(doubleQuoteSmuggle), []);
  assert.deepEqual(extractHtmlAnchorIds(singleQuoteSmuggle), []);
  assert.equal(inspectHtmlAnchorIds(doubleQuoteSmuggle).malformed, true);
  assert.equal(inspectHtmlAnchorIds(singleQuoteSmuggle).malformed, true);
  assert.deepEqual(inspectHtmlAnchorIds(doubleQuoteSmuggle).ids, []);
  assert.deepEqual(inspectHtmlAnchorIds(singleQuoteSmuggle).ids, []);

  // Valid quoted greater-than and normal independent a id remain accepted.
  assert.deepEqual(
    extractHtmlAnchorIds('<a title="x > y" id="ccm-k-skill-demo-entry"></a>'),
    ['ccm-k-skill-demo-entry'],
  );
  assert.equal(
    inspectHtmlAnchorIds('<a title="x > y" id="ccm-k-skill-demo-entry"></a>').malformed,
    false,
  );
  assert.deepEqual(
    extractHtmlAnchorIds('<a id="ccm-k-skill-demo-entry"></a>'),
    ['ccm-k-skill-demo-entry'],
  );

  // Nested `<` that is not an a-tag must remain not-an-a-tag (advance), not malformed.
  assert.equal(inspectHtmlAnchorIds('<div><span>x</span></div>').malformed, false);
  assert.deepEqual(extractHtmlAnchorIds('<div><a id="ccm-k-skill-demo-entry"></a></div>'), [
    'ccm-k-skill-demo-entry',
  ]);

  withTempDir((root) => {
    const payload = path.join(root, 'malformed-smuggle');
    fs.mkdirSync(path.join(payload, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      path.join(payload, 'skills', 'demo', 'SKILL.md'),
      [
        '# Unclosed quote nested a smuggle',
        '',
        doubleQuoteSmuggle,
        '',
        '[smuggled](#ccm-k-point-smuggled)',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'claude-code',
      mode: 'canonical',
      payloadRoot: payload,
      repoRoot,
    });
    assert.equal(result.ok, false);
    assert.equal(
      result.diagnostics.some((item) => item.code === 'SKG-HOST-ANCHOR-MALFORMED'),
      true,
    );
    assert.equal(
      result.diagnostics.some(
        (item) =>
          item.code === 'SKG-HOST-ANCHOR-UNVERIFIABLE' &&
          /ccm-k-point-smuggled/.test(item.message),
      ),
      true,
    );
  });

  withTempDir((root) => {
    const payload = path.join(root, 'malformed-before-good');
    fs.mkdirSync(path.join(payload, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      path.join(payload, 'skills', 'demo', 'SKILL.md'),
      [
        '# Malformed before well-formed must fail closed',
        '',
        singleQuoteSmuggle,
        '<a id="ccm-k-skill-demo-entry"></a>',
        '',
        '[later good](#ccm-k-skill-demo-entry)',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'claude-code',
      mode: 'canonical',
      payloadRoot: payload,
      repoRoot,
    });
    // Must not silently recover by accepting the later well-formed anchor alone.
    assert.equal(result.ok, false);
    assert.equal(
      result.diagnostics.some((item) => item.code === 'SKG-HOST-ANCHOR-MALFORMED'),
      true,
    );
  });
});

test('SKG-HOST-11: payload path symlink escaping fixture root fails closed', async () => {
  const { probeHostPayload } = await import(
    '../../scripts/skill-knowledge/host-portability/probe.mjs'
  );

  withTempDir((root) => {
    const payload = path.join(root, 'payload');
    const outside = path.join(root, 'outside.md');
    fs.mkdirSync(path.join(payload, 'skills', 'demo'), { recursive: true });
    fs.writeFileSync(
      outside,
      [
        '# Outside fixture root',
        '',
        '<a id="ccm-k-point-verification-endpoint-principle"></a>',
        '',
      ].join('\n'),
    );
    fs.symlinkSync(outside, path.join(payload, 'skills', 'demo', 'escape.md'));
    fs.writeFileSync(
      path.join(payload, 'skills', 'demo', 'SKILL.md'),
      [
        '# Symlink escape',
        '',
        '[escape](./escape.md#ccm-k-point-verification-endpoint-principle)',
        '<a id="ccm-k-skill-demo-entry"></a>',
        '',
      ].join('\n'),
    );

    const result = probeHostPayload({
      host: 'cursor',
      mode: 'canonical',
      payloadRoot: payload,
      repoRoot,
    });
    assert.equal(result.ok, false);
    assert.equal(
      result.diagnostics.some((item) => item.code === 'SKG-HOST-LINK-TARGET-MISSING'),
      true,
    );
    assert.equal(
      result.diagnostics.some((item) =>
        /symlink|realpath|escapes payload root/i.test(item.message),
      ),
      true,
    );
  });
});

test('SKG-HOST-12: Codex token facts use ${PLUGIN_ROOT}; nested contract is deep-frozen', async () => {
  const {
    HOST_ADAPTER_CONTRACT,
    getHostAdapterContract,
  } = await import('../../scripts/skill-knowledge/host-portability/adapter-contract.mjs');

  assert.equal(HOST_ADAPTER_CONTRACT.hosts.codex.path_tokens.plugin_root, '${PLUGIN_ROOT}');
  assert.equal(
    HOST_ADAPTER_CONTRACT.hosts.codex.path_tokens.rejected_fiction_tokens.includes(
      '${CODEX_PLUGIN_ROOT}',
    ),
    true,
  );
  assert.equal(
    JSON.stringify(HOST_ADAPTER_CONTRACT).includes('CODEX_PLUGIN_ROOT') &&
      !JSON.stringify(HOST_ADAPTER_CONTRACT.hosts.codex.path_tokens.plugin_root).includes(
        'CODEX_PLUGIN_ROOT',
      ),
    true,
  );
  assert.notEqual(
    HOST_ADAPTER_CONTRACT.hosts.codex.path_tokens.plugin_root,
    '${CODEX_PLUGIN_ROOT}',
  );

  assert.throws(() => {
    HOST_ADAPTER_CONTRACT.product_hosts.push('evil-host');
  }, /typeerror|read only|not extensible|cannot/i);
  assert.throws(() => {
    HOST_ADAPTER_CONTRACT.worker_allowlist.push('claude-code');
  }, /typeerror|read only|not extensible|cannot/i);
  assert.throws(() => {
    HOST_ADAPTER_CONTRACT.hosts.codex.evidence.push({
      kind: 'live-click-through',
      path: 'evil',
    });
  }, /typeerror|read only|not extensible|cannot/i);
  assert.throws(() => {
    HOST_ADAPTER_CONTRACT.hosts.codex.path_tokens.rejected_fiction_tokens.push('${EVIL}');
  }, /typeerror|read only|not extensible|cannot/i);
  assert.throws(() => {
    HOST_ADAPTER_CONTRACT.hosts.cursor.path_tokens.plugin_root = '${CURSOR_PLUGIN_ROOT}';
  }, /typeerror|read only|not extensible|cannot/i);

  const copy = getHostAdapterContract();
  assert.deepEqual(copy.product_hosts, [...PRODUCT_HOSTS]);
  assert.throws(() => {
    copy.product_hosts.push('mutated');
  }, /typeerror|read only|not extensible|cannot/i);
  assert.throws(() => {
    copy.hosts['claude-code'].evidence[0].kind = 'live-click-through';
  }, /typeerror|read only|not extensible|cannot/i);
});

test('SKG-HOST-13: assertHostAdapterContract validates the candidate, not a canonical stamp', async () => {
  const {
    HOST_ADAPTER_CONTRACT,
    assertHostAdapterContract,
  } = await import('../../scripts/skill-knowledge/host-portability/adapter-contract.mjs');

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  assertHostAdapterContract(HOST_ADAPTER_CONTRACT);
  assertHostAdapterContract(clone(HOST_ADAPTER_CONTRACT));

  // Replace Cursor profile body with Claude profile (keep Cursor worker_eligible).
  const swapped = clone(HOST_ADAPTER_CONTRACT);
  swapped.hosts.cursor = {
    ...clone(HOST_ADAPTER_CONTRACT.hosts['claude-code']),
    worker_eligible: true,
  };
  assert.throws(
    () => assertHostAdapterContract(swapped),
    /cursor|profile|digest|expectation|path.token|canonical/i,
  );

  // Alter Cursor path tokens while attaching a recomputed self-declared fingerprint.
  const altered = clone(HOST_ADAPTER_CONTRACT);
  altered.hosts.cursor.path_tokens = clone(
    HOST_ADAPTER_CONTRACT.hosts['claude-code'].path_tokens,
  );
  altered.hosts.cursor.profile_fingerprint = JSON.stringify({
    host: 'cursor',
    path_tokens: altered.hosts.cursor.path_tokens,
    mechanism: altered.hosts.cursor.path_tokens.plugin_root_mechanism,
  });
  assert.throws(
    () => assertHostAdapterContract(altered),
    /cursor|profile|digest|expectation|path.token|canonical|fingerprint/i,
  );

  // Path-token-only swap must also fail (evidence left alone).
  const tokenSwap = clone(HOST_ADAPTER_CONTRACT);
  tokenSwap.hosts.cursor.path_tokens = clone(
    HOST_ADAPTER_CONTRACT.hosts['claude-code'].path_tokens,
  );
  assert.throws(
    () => assertHostAdapterContract(tokenSwap),
    /cursor|profile|digest|expectation|path.token|canonical/i,
  );
});
