'use strict';

// project-skill.cjs — the single skill-projection SSOT shared by sync-plugin-dist.sh and the
// update-*-attestations scripts.
//
// Why this module exists (issue #163): the attestation registries
// (plugin/src/skills/provider-guidance-runtime.json and
// plugin/src/skills/pacing-and-estimation/read-only-capability.json) used to be regenerated by
// reading the already-projected plugin/dist trees. But sync refuses to write a new dist tree until
// its fingerprint matches the registry, so when an attested skill's canonical content or file set
// changed the registry could never move: sync's assert rejected the new staging tree (dist stayed
// stale) and update read the stale dist (registry stayed stale) — a sync↔update deadlock.
//
// The fix dissolves the circular dependency at its root: registry regeneration now projects the
// canonical source itself (via planSkillProjection + applySkillProjection here) and fingerprints
// that fresh projection, instead of reading dist. sync uses the exact same two functions to build
// the dist it asserts, so a registry recomputed from a fresh projection always matches what sync
// projects. There is a single projection implementation — the update path and the assert path can
// never drift.
//
// This module performs NO attestation assert and NO dist rename. Callers decide: sync asserts the
// projected tree against the committed registry then renames staging into dist; the update scripts
// project into a scratch dir purely to fingerprint it. sync's assert-on gate is therefore never
// weakened or bypassed — it stays exactly as it was and remains the CI safety net.

const fs = require('node:fs');
const path = require('node:path');
const {
  assertPacingCanonicalTemplate,
  loadPacingReadOnlyRegistry,
  renderPacingReadOnlyCapability,
} = require('./pacing-read-only-capability.cjs');

// Skill-tree entries that never cross the projection boundary (maintainer prose / co-located design
// docs / eval fixtures). Kept identical to sync's historical SKILL_DIST_EXCLUDES.
const SKILL_DIST_EXCLUDES = ['AGENTS.md', 'CLAUDE.md', '.design', 'evals'];

function copyDir(from, to, options = {}) {
  const exclude = new Set(options.exclude || []);
  const replacements = options.replacements || new Map();
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    if (exclude.has(entry.name)) continue;
    if (entry.name === '.DS_Store' || entry.name === '.gitkeep') continue;
    const sourcePath = path.join(from, entry.name);
    const targetPath = path.join(to, entry.name);
    if (entry.isDirectory()) {
      copyDir(sourcePath, targetPath, options);
    } else if (entry.isFile()) {
      fs.mkdirSync(path.dirname(targetPath), { recursive: true });
      if (replacements.size > 0 && entry.name.endsWith('.md')) {
        let text = fs.readFileSync(sourcePath, 'utf8');
        for (const [token, replacement] of replacements.entries()) {
          text = text.split(token).join(replacement);
        }
        const unresolved = text.match(/\{\{[A-Z0-9_]+\}\}/);
        if (unresolved) {
          throw new Error(`unresolved adapter slot ${unresolved[0]} in ${sourcePath}`);
        }
        fs.writeFileSync(targetPath, text);
      } else {
        fs.copyFileSync(sourcePath, targetPath);
      }
      fs.chmodSync(targetPath, fs.statSync(sourcePath).mode);
    }
  }
}

function requireDir(dir) {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
    throw new Error(`missing ${dir}`);
  }
}

function readStrategyMode(file) {
  const text = fs.readFileSync(file, 'utf8');
  const match = text.match(/^\s*mode:\s*([A-Za-z0-9_-]+)\s*$/m);
  return match ? match[1] : 'copy';
}

function readSlotReplacements(file, baseDir) {
  const text = fs.readFileSync(file, 'utf8');
  const replacements = new Map();
  let inSection = false;
  let sectionIndent = 0;
  for (const line of text.split(/\r?\n/)) {
    const section = line.match(/^(\s*)slot_replacements:\s*$/);
    if (section) {
      inSection = true;
      sectionIndent = section[1].length;
      continue;
    }
    if (!inSection) continue;
    if (/^\s*$/.test(line) || /^\s*#/.test(line)) continue;
    const indent = line.match(/^(\s*)/)[1].length;
    if (indent <= sectionIndent) break;
    const match = line.match(/^\s*["']?(\{\{[A-Z0-9_]+\}\})["']?\s*:\s*["']?([^"'\n]+)["']?\s*$/);
    if (!match) continue;
    const token = match[1];
    const rel = match[2].trim();
    const replacementPath = path.join(baseDir, rel);
    if (!fs.existsSync(replacementPath)) {
      throw new Error(`missing slot replacement ${replacementPath} for ${token} in ${file}`);
    }
    replacements.set(token, fs.readFileSync(replacementPath, 'utf8').replace(/\s+$/u, ''));
  }
  return replacements;
}

function readYamlString(file, key) {
  const text = fs.readFileSync(file, 'utf8');
  const match = text.match(new RegExp(`^\\s*${key}:\\s*["']?([^"'\\n]+)["']?\\s*$`, 'm'));
  return match ? match[1].trim() : null;
}

function readYamlList(file, key) {
  const text = fs.readFileSync(file, 'utf8');
  const values = [];
  let inSection = false;
  let sectionIndent = 0;
  for (const line of text.split(/\r?\n/)) {
    const section = line.match(new RegExp(`^(\\s*)${key}:\\s*$`));
    if (section) {
      inSection = true;
      sectionIndent = section[1].length;
      continue;
    }
    if (!inSection) continue;
    if (/^\s*$/.test(line) || /^\s*#/.test(line)) continue;
    const indent = line.match(/^(\s*)/)[1].length;
    if (indent <= sectionIndent) break;
    const item = line.match(/^\s*-\s*["']?([^"'\n]+)["']?\s*$/);
    if (!item) continue;
    values.push(item[1].trim());
  }
  return values;
}

function readIndentedYamlBlock(text, key, indent = 0) {
  const lines = text.split(/\r?\n/);
  const prefix = ' '.repeat(indent);
  const start = lines.findIndex((line) => line === `${prefix}${key}:`);
  if (start < 0) return null;
  const block = [];
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (/^\s*$/u.test(line) || /^\s*#/u.test(line)) {
      block.push(line);
      continue;
    }
    const lineIndent = line.match(/^(\s*)/u)[1].length;
    if (lineIndent <= indent) break;
    block.push(line);
  }
  return block.join('\n');
}

function readReadOnlyCapabilityContract(file) {
  const text = fs.readFileSync(file, 'utf8');
  const runtimeContracts = readIndentedYamlBlock(text, 'runtime_contracts');
  if (runtimeContracts === null) return null;
  const contract = readIndentedYamlBlock(runtimeContracts, 'read_only_capability', 2);
  if (contract === null) return null;
  const value = (key) => {
    const match = contract.match(
      new RegExp(`^ {4}${key}:\\s*["']?([^"'\\n]+)["']?\\s*$`, 'm'),
    );
    if (!match) throw new Error(`missing runtime_contracts.read_only_capability.${key} in ${file}`);
    return match[1].trim();
  };
  return {
    registry: value('registry'),
    slot: value('slot'),
    host: value('host'),
  };
}

function readProviderGuidanceContract(file) {
  const text = fs.readFileSync(file, 'utf8');
  const runtimeContracts = readIndentedYamlBlock(text, 'runtime_contracts');
  if (runtimeContracts === null) return null;
  const contract = readIndentedYamlBlock(runtimeContracts, 'provider_guidance', 2);
  if (contract === null) return null;
  const value = (key) => {
    const match = contract.match(
      new RegExp(`^ {4}${key}:\\s*["']?([^"'\\n]+)["']?\\s*$`, 'm'),
    );
    if (!match) throw new Error(`missing runtime_contracts.provider_guidance.${key} in ${file}`);
    return match[1].trim();
  };
  return {
    registry: value('registry'),
    host: value('host'),
    skill: value('skill'),
  };
}

function projectText(text, replacements, sourcePath) {
  let projected = text;
  for (const [token, replacement] of replacements.entries()) {
    projected = projected.split(token).join(replacement);
  }
  const unresolved = projected.match(/\{\{[A-Z0-9_]+\}\}/);
  if (unresolved) {
    throw new Error(`unresolved adapter slot ${unresolved[0]} in ${sourcePath}`);
  }
  return projected;
}

function copyFileWithMode(from, to, replacements = new Map()) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  if (replacements.size > 0 && from.endsWith('.md')) {
    fs.writeFileSync(to, projectText(fs.readFileSync(from, 'utf8'), replacements, from));
  } else {
    fs.copyFileSync(from, to);
  }
  fs.chmodSync(to, fs.statSync(from).mode);
}

function copyCanonicalIncludes(base, target, includes, replacements) {
  for (const rel of includes) {
    const sourcePath = path.join(base, rel);
    const targetPath = path.join(target, rel);
    if (!fs.existsSync(sourcePath)) throw new Error(`missing include ${sourcePath}`);
    const stat = fs.statSync(sourcePath);
    if (stat.isDirectory()) {
      copyDir(sourcePath, targetPath, {
        exclude: ['AGENTS.md', 'CLAUDE.md'],
        replacements,
      });
    } else if (stat.isFile()) {
      copyFileWithMode(sourcePath, targetPath, replacements);
    } else {
      throw new Error(`unsupported include type ${sourcePath}`);
    }
  }
}

function removeProjectedPaths(target, rels) {
  for (const rel of rels) {
    const targetPath = path.join(target, rel);
    if (!fs.existsSync(targetPath)) continue;
    fs.rmSync(targetPath, { recursive: true, force: true });
  }
}

// planSkillProjection reads one skill's adapter strategy for one host and prepares everything the
// projection needs, WITHOUT touching any output directory. It renders the pacing read-only slot when
// the strategy declares a read_only_capability contract (the rendered body is a pure function of the
// registry's non-digest fields, so it is stable across a registry regen), and returns the loaded
// pacing registry + rendered body so the caller can attest them. It deliberately does NOT load the
// provider-guidance registry (that registry is not needed to project — the projection is a plain
// copy — it is only needed for the assert, which the caller owns) and it deliberately does NOT run
// assertPacingRenderedArtifact (that is an assert against the committed registry, which regeneration
// must not enforce). Returns null contracts / mode:'planned' unchanged for non-attested skills.
function planSkillProjection({ repoRoot, host, skill }) {
  const skillsSrc = path.join(repoRoot, 'plugin/src/skills');
  const skillDir = path.join(skillsSrc, skill);
  const canonical = path.join(skillDir, 'canonical');
  const strategy = path.join(skillDir, 'adapters', host, 'strategy.yaml');
  requireDir(canonical);
  if (!fs.existsSync(strategy)) throw new Error(`missing ${strategy}`);
  const mode = readStrategyMode(strategy);
  const slotReplacements = readSlotReplacements(strategy, skillDir);
  const readOnlyContract = readReadOnlyCapabilityContract(strategy);
  const providerGuidanceContract = readProviderGuidanceContract(strategy);

  let pacingRegistry = null;
  let pacingRenderedBody = null;
  if (readOnlyContract) {
    if (readOnlyContract.host !== host) {
      throw new Error(
        `runtime read-only capability host ${readOnlyContract.host} does not match ${host} in ${strategy}`,
      );
    }
    if (slotReplacements.has(readOnlyContract.slot)) {
      throw new Error(`duplicate replacement for ${readOnlyContract.slot} in ${strategy}`);
    }
    const registryPath = path.join(skillDir, readOnlyContract.registry);
    if (!fs.existsSync(registryPath)) throw new Error(`missing ${registryPath}`);
    pacingRegistry = loadPacingReadOnlyRegistry(registryPath);
    if (readOnlyContract.slot !== pacingRegistry.slot) {
      throw new Error(
        `runtime read-only capability slot ${readOnlyContract.slot} does not match registry ${pacingRegistry.slot}`,
      );
    }
    assertPacingCanonicalTemplate(
      fs.readFileSync(path.join(canonical, 'SKILL.md'), 'utf8'),
      pacingRegistry.slot,
    );
    pacingRenderedBody = renderPacingReadOnlyCapability(pacingRegistry, readOnlyContract.host);
    slotReplacements.set(pacingRegistry.slot, pacingRenderedBody.replace(/\s+$/u, ''));
  }

  let providerGuidanceRegistryPath = null;
  if (providerGuidanceContract) {
    if (providerGuidanceContract.host !== host) {
      throw new Error(
        `runtime provider guidance host ${providerGuidanceContract.host} does not match ${host} in ${strategy}`,
      );
    }
    if (providerGuidanceContract.skill !== skill) {
      throw new Error(
        `runtime provider guidance skill ${providerGuidanceContract.skill} does not match ${skill} in ${strategy}`,
      );
    }
    providerGuidanceRegistryPath = path.join(skillDir, providerGuidanceContract.registry);
    if (!fs.existsSync(providerGuidanceRegistryPath)) {
      throw new Error(`missing ${providerGuidanceRegistryPath}`);
    }
  }

  return {
    skill,
    host,
    skillDir,
    canonical,
    strategy,
    mode,
    slotReplacements,
    readOnlyContract,
    providerGuidanceContract,
    providerGuidanceRegistryPath,
    pacingRegistry,
    pacingRenderedBody,
    attested: Boolean(readOnlyContract || providerGuidanceContract),
  };
}

// applySkillProjection materializes the plan into targetDir (a scratch/staging dir or the real dist
// tree). It is projection only: no attestation assert, no rename. mode:'planned' is a no-op (the
// caller is expected to skip it).
function applySkillProjection(plan, targetDir) {
  const { mode, canonical, skillDir, strategy, slotReplacements } = plan;
  if (mode === 'planned') return;
  if (mode === 'copy') {
    copyDir(canonical, targetDir, {
      exclude: SKILL_DIST_EXCLUDES,
      replacements: slotReplacements,
    });
    removeProjectedPaths(targetDir, readYamlList(strategy, 'exclude_canonical'));
    copyCanonicalIncludes(
      skillDir,
      targetDir,
      readYamlList(strategy, 'include_adapter'),
      slotReplacements,
    );
  } else if (mode === 'unsupported_stub') {
    const stub = path.join(skillDir, 'adapters', plan.host, 'stub');
    requireDir(stub);
    copyDir(stub, targetDir, {
      exclude: SKILL_DIST_EXCLUDES,
    });
  } else if (mode === 'partial_overlay') {
    const sourceRel = readYamlString(strategy, 'source') || path.join('adapters', plan.host, 'partial');
    const partial = path.join(skillDir, sourceRel);
    requireDir(partial);
    copyDir(partial, targetDir, {
      exclude: SKILL_DIST_EXCLUDES,
    });
    copyCanonicalIncludes(
      canonical,
      targetDir,
      readYamlList(strategy, 'include_canonical'),
      slotReplacements,
    );
  } else {
    throw new Error(`unsupported projection mode "${mode}" in ${strategy}`);
  }
}

module.exports = {
  SKILL_DIST_EXCLUDES,
  applySkillProjection,
  copyCanonicalIncludes,
  copyDir,
  copyFileWithMode,
  planSkillProjection,
  projectText,
  readIndentedYamlBlock,
  readProviderGuidanceContract,
  readReadOnlyCapabilityContract,
  readSlotReplacements,
  readStrategyMode,
  readYamlList,
  readYamlString,
  removeProjectedPaths,
  requireDir,
};
